// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import org.apache.commons.lang3.exception.ExceptionUtils;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DeleteMqttClientObject extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __PubSubObject;
	private mqttclient.proxies.PubSub PubSubObject;

	public DeleteMqttClientObject(IContext context, IMendixObject PubSubObject)
	{
		super(context);
		this.__PubSubObject = PubSubObject;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.PubSubObject = __PubSubObject == null ? null : mqttclient.proxies.PubSub.initialize(getContext(), __PubSubObject);

		// BEGIN USER CODE
		try {
			MqttConnector handler = new MqttConnector();
			handler.deleteClientObject(this.PubSubObject.getBrokerHost(), this.PubSubObject.getBrokerPort().longValue(), 
					this.PubSubObject.getUserName(), this.PubSubObject.getTopicName(), this.PubSubObject.getPubOrSub());

		} catch (Exception e) {
			Core.getLogger("MqttConnector").error(ExceptionUtils.getStackTrace(e));
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteMqttClientObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
