// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DeleteBrokerConnection extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __BrokerConfig;
	private mqttclient.proxies.BrokerConfig BrokerConfig;

	public DeleteBrokerConnection(IContext context, IMendixObject BrokerConfig)
	{
		super(context);
		this.__BrokerConfig = BrokerConfig;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.BrokerConfig = __BrokerConfig == null ? null : mqttclient.proxies.BrokerConfig.initialize(getContext(), __BrokerConfig);

		// BEGIN USER CODE
		if(this.BrokerConfig != null)
        {
            MqttConnector.deleteConnection(this.BrokerConfig);
        }
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteBrokerConnection";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
