// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import org.apache.commons.lang3.exception.ExceptionUtils;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class InitializeMqttConnection extends CustomJavaAction<java.lang.Void>
{
	private java.util.List<IMendixObject> __BrokerConfigList;
	private java.util.List<mqttclient.proxies.BrokerConfig> BrokerConfigList;

	public InitializeMqttConnection(IContext context, java.util.List<IMendixObject> BrokerConfigList)
	{
		super(context);
		this.__BrokerConfigList = BrokerConfigList;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.BrokerConfigList = new java.util.ArrayList<mqttclient.proxies.BrokerConfig>();
		if (__BrokerConfigList != null)
			for (IMendixObject __BrokerConfigListElement : __BrokerConfigList)
				this.BrokerConfigList.add(mqttclient.proxies.BrokerConfig.initialize(getContext(), __BrokerConfigListElement));

		// BEGIN USER CODE
		this.BrokerConfigList.forEach(brokerConfig -> 
		        {
                    try {
                        MqttConnector.initializeConnectionOnStartup(brokerConfig);
                    } catch (Exception e) {
                        MqttConnector.logger.error(String.format("Exception encountered while initializing connection for the broker: %s%n%s", 
                                MqttConnector.getKeyForBrokerConfig(brokerConfig), ExceptionUtils.getStackTrace(e)));
                        throw new MendixRuntimeException(e);
                    }
                });
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitializeMqttConnection";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
