// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import org.apache.commons.lang3.exception.ExceptionUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class MqttPublish extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __MqttConfigObject;
	private mqttclient.proxies.MqttConfig MqttConfigObject;
	private java.lang.String payload;

	public MqttPublish(IContext context, IMendixObject MqttConfigObject, java.lang.String payload)
	{
		super(context);
		this.__MqttConfigObject = MqttConfigObject;
		this.payload = payload;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.MqttConfigObject = __MqttConfigObject == null ? null : mqttclient.proxies.MqttConfig.initialize(getContext(), __MqttConfigObject);

		// BEGIN USER CODE
		try {
        	MqttConnector.publish(this.MqttConfigObject, this.MqttConfigObject.getMqttConfig_BrokerConfig(), payload);
        	return true;
        } catch (Exception e) {
        	Core.getLogger("MqttConnector").error(ExceptionUtils.getStackTrace(e));
            return false;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MqttPublish";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
