// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import org.apache.commons.lang3.exception.ExceptionUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import mqttclient.proxies.Subscription;

public class MqttSubscribe extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __MqttConfigObject;
	private mqttclient.proxies.MqttConfig MqttConfigObject;
	private java.lang.String OnMessageMicroflow;

	public MqttSubscribe(IContext context, IMendixObject MqttConfigObject, java.lang.String OnMessageMicroflow)
	{
		super(context);
		this.__MqttConfigObject = MqttConfigObject;
		this.OnMessageMicroflow = OnMessageMicroflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.MqttConfigObject = __MqttConfigObject == null ? null : mqttclient.proxies.MqttConfig.initialize(getContext(), __MqttConfigObject);

		// BEGIN USER CODE
		try {
			MqttConnector.subscribe(this.MqttConfigObject, this.MqttConfigObject.getMqttConfig_BrokerConfig(), this.OnMessageMicroflow);
			Subscription subscription = this.MqttConfigObject.getMqttConfig_Subscription();
			// Creating the subscription object
			if (subscription == null)
			{
				Subscription newSubscriptionObj = new Subscription(context());
				newSubscriptionObj.setOnMessageMicroflow(this.OnMessageMicroflow);
				newSubscriptionObj.setMqttConfig_Subscription(this.MqttConfigObject);
				newSubscriptionObj.commit();
			}
			else 
			{
				// Updating the existing subscription object
				String oldOnMsgMicroflow = subscription.getOnMessageMicroflow();
				if (!(oldOnMsgMicroflow.equals(subscription.getOnMessageMicroflow())))
				{
					subscription.setOnMessageMicroflow(this.OnMessageMicroflow);
					subscription.commit();
				}
			}
			return true;
		} catch (Exception e) {
			Core.getLogger("MqttConnector").error(ExceptionUtils.getStackTrace(e));
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MqttSubscribe";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
