// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import org.apache.commons.lang3.exception.ExceptionUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttConnector;
import mqttclient.proxies.Subscription;

/**
 * 
 * Returns true if successful
 * if an exception occurs during the unsubscribe this activity will return a false
 */
public class MqttUnsubscribe extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __MqttConfigObject;
	private mqttclient.proxies.MqttConfig MqttConfigObject;

	public MqttUnsubscribe(IContext context, IMendixObject MqttConfigObject)
	{
		super(context);
		this.__MqttConfigObject = MqttConfigObject;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.MqttConfigObject = __MqttConfigObject == null ? null : mqttclient.proxies.MqttConfig.initialize(getContext(), __MqttConfigObject);

		// BEGIN USER CODE
		try {
			MqttConnector.unsubscribe(this.MqttConfigObject, this.MqttConfigObject.getMqttConfig_BrokerConfig());
			return true;
		} catch (Exception e) {
			Core.getLogger("MqttConnector").error(ExceptionUtils.getStackTrace(e));
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MqttUnsubscribe";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
