// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies;

public class PubSub
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pubSubMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MqttClient.PubSub";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConfigurationName("ConfigurationName"),
		PubOrSub("PubOrSub"),
		SubOrUnSub("SubOrUnSub"),
		BrokerHost("BrokerHost"),
		BrokerPort("BrokerPort"),
		BrokerOrganization("BrokerOrganization"),
		Timeout("Timeout"),
		UserName("UserName"),
		Password("Password"),
		TopicName("TopicName"),
		Payload("Payload"),
		CA("CA"),
		ClientCertificate("ClientCertificate"),
		ClientKey("ClientKey"),
		CertificatePassword("CertificatePassword"),
		Qos("Qos");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PubSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MqttClient.PubSub"));
	}

	protected PubSub(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pubSubMendixObject)
	{
		if (pubSubMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MqttClient.PubSub", pubSubMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MqttClient.PubSub");

		this.pubSubMendixObject = pubSubMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PubSub.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mqttclient.proxies.PubSub initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mqttclient.proxies.PubSub.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mqttclient.proxies.PubSub initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mqttclient.proxies.PubSub(context, mendixObject);
	}

	public static mqttclient.proxies.PubSub load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mqttclient.proxies.PubSub.initialize(context, mendixObject);
	}

	public static java.util.List<mqttclient.proxies.PubSub> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mqttclient.proxies.PubSub> result = new java.util.ArrayList<mqttclient.proxies.PubSub>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MqttClient.PubSub" + xpathConstraint))
			result.add(mqttclient.proxies.PubSub.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ConfigurationName
	 */
	public final java.lang.String getConfigurationName()
	{
		return getConfigurationName(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigurationName
	 */
	public final java.lang.String getConfigurationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfigurationName.toString());
	}

	/**
	 * Set value of ConfigurationName
	 * @param configurationname
	 */
	public final void setConfigurationName(java.lang.String configurationname)
	{
		setConfigurationName(getContext(), configurationname);
	}

	/**
	 * Set value of ConfigurationName
	 * @param context
	 * @param configurationname
	 */
	public final void setConfigurationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configurationname)
	{
		getMendixObject().setValue(context, MemberNames.ConfigurationName.toString(), configurationname);
	}

	/**
	 * Set value of PubOrSub
	 * @param puborsub
	 */
	public final mqttclient.proxies.Enum_PubOrSub getPubOrSub()
	{
		return getPubOrSub(getContext());
	}

	/**
	 * @param context
	 * @return value of PubOrSub
	 */
	public final mqttclient.proxies.Enum_PubOrSub getPubOrSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PubOrSub.toString());
		if (obj == null)
			return null;

		return mqttclient.proxies.Enum_PubOrSub.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PubOrSub
	 * @param puborsub
	 */
	public final void setPubOrSub(mqttclient.proxies.Enum_PubOrSub puborsub)
	{
		setPubOrSub(getContext(), puborsub);
	}

	/**
	 * Set value of PubOrSub
	 * @param context
	 * @param puborsub
	 */
	public final void setPubOrSub(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.Enum_PubOrSub puborsub)
	{
		if (puborsub != null)
			getMendixObject().setValue(context, MemberNames.PubOrSub.toString(), puborsub.toString());
		else
			getMendixObject().setValue(context, MemberNames.PubOrSub.toString(), null);
	}

	/**
	 * @return value of SubOrUnSub
	 */
	public final java.lang.Boolean getSubOrUnSub()
	{
		return getSubOrUnSub(getContext());
	}

	/**
	 * @param context
	 * @return value of SubOrUnSub
	 */
	public final java.lang.Boolean getSubOrUnSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SubOrUnSub.toString());
	}

	/**
	 * Set value of SubOrUnSub
	 * @param suborunsub
	 */
	public final void setSubOrUnSub(java.lang.Boolean suborunsub)
	{
		setSubOrUnSub(getContext(), suborunsub);
	}

	/**
	 * Set value of SubOrUnSub
	 * @param context
	 * @param suborunsub
	 */
	public final void setSubOrUnSub(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean suborunsub)
	{
		getMendixObject().setValue(context, MemberNames.SubOrUnSub.toString(), suborunsub);
	}

	/**
	 * @return value of BrokerHost
	 */
	public final java.lang.String getBrokerHost()
	{
		return getBrokerHost(getContext());
	}

	/**
	 * @param context
	 * @return value of BrokerHost
	 */
	public final java.lang.String getBrokerHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrokerHost.toString());
	}

	/**
	 * Set value of BrokerHost
	 * @param brokerhost
	 */
	public final void setBrokerHost(java.lang.String brokerhost)
	{
		setBrokerHost(getContext(), brokerhost);
	}

	/**
	 * Set value of BrokerHost
	 * @param context
	 * @param brokerhost
	 */
	public final void setBrokerHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brokerhost)
	{
		getMendixObject().setValue(context, MemberNames.BrokerHost.toString(), brokerhost);
	}

	/**
	 * @return value of BrokerPort
	 */
	public final java.lang.Integer getBrokerPort()
	{
		return getBrokerPort(getContext());
	}

	/**
	 * @param context
	 * @return value of BrokerPort
	 */
	public final java.lang.Integer getBrokerPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BrokerPort.toString());
	}

	/**
	 * Set value of BrokerPort
	 * @param brokerport
	 */
	public final void setBrokerPort(java.lang.Integer brokerport)
	{
		setBrokerPort(getContext(), brokerport);
	}

	/**
	 * Set value of BrokerPort
	 * @param context
	 * @param brokerport
	 */
	public final void setBrokerPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer brokerport)
	{
		getMendixObject().setValue(context, MemberNames.BrokerPort.toString(), brokerport);
	}

	/**
	 * @return value of BrokerOrganization
	 */
	public final java.lang.String getBrokerOrganization()
	{
		return getBrokerOrganization(getContext());
	}

	/**
	 * @param context
	 * @return value of BrokerOrganization
	 */
	public final java.lang.String getBrokerOrganization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrokerOrganization.toString());
	}

	/**
	 * Set value of BrokerOrganization
	 * @param brokerorganization
	 */
	public final void setBrokerOrganization(java.lang.String brokerorganization)
	{
		setBrokerOrganization(getContext(), brokerorganization);
	}

	/**
	 * Set value of BrokerOrganization
	 * @param context
	 * @param brokerorganization
	 */
	public final void setBrokerOrganization(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brokerorganization)
	{
		getMendixObject().setValue(context, MemberNames.BrokerOrganization.toString(), brokerorganization);
	}

	/**
	 * @return value of Timeout
	 */
	public final java.lang.Long getTimeout()
	{
		return getTimeout(getContext());
	}

	/**
	 * @param context
	 * @return value of Timeout
	 */
	public final java.lang.Long getTimeout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Timeout.toString());
	}

	/**
	 * Set value of Timeout
	 * @param timeout
	 */
	public final void setTimeout(java.lang.Long timeout)
	{
		setTimeout(getContext(), timeout);
	}

	/**
	 * Set value of Timeout
	 * @param context
	 * @param timeout
	 */
	public final void setTimeout(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long timeout)
	{
		getMendixObject().setValue(context, MemberNames.Timeout.toString(), timeout);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of TopicName
	 */
	public final java.lang.String getTopicName()
	{
		return getTopicName(getContext());
	}

	/**
	 * @param context
	 * @return value of TopicName
	 */
	public final java.lang.String getTopicName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TopicName.toString());
	}

	/**
	 * Set value of TopicName
	 * @param topicname
	 */
	public final void setTopicName(java.lang.String topicname)
	{
		setTopicName(getContext(), topicname);
	}

	/**
	 * Set value of TopicName
	 * @param context
	 * @param topicname
	 */
	public final void setTopicName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String topicname)
	{
		getMendixObject().setValue(context, MemberNames.TopicName.toString(), topicname);
	}

	/**
	 * @return value of Payload
	 */
	public final java.lang.String getPayload()
	{
		return getPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of Payload
	 */
	public final java.lang.String getPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payload.toString());
	}

	/**
	 * Set value of Payload
	 * @param payload
	 */
	public final void setPayload(java.lang.String payload)
	{
		setPayload(getContext(), payload);
	}

	/**
	 * Set value of Payload
	 * @param context
	 * @param payload
	 */
	public final void setPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.Payload.toString(), payload);
	}

	/**
	 * @return value of CA
	 */
	public final java.lang.String getCA()
	{
		return getCA(getContext());
	}

	/**
	 * @param context
	 * @return value of CA
	 */
	public final java.lang.String getCA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CA.toString());
	}

	/**
	 * Set value of CA
	 * @param ca
	 */
	public final void setCA(java.lang.String ca)
	{
		setCA(getContext(), ca);
	}

	/**
	 * Set value of CA
	 * @param context
	 * @param ca
	 */
	public final void setCA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ca)
	{
		getMendixObject().setValue(context, MemberNames.CA.toString(), ca);
	}

	/**
	 * @return value of ClientCertificate
	 */
	public final java.lang.String getClientCertificate()
	{
		return getClientCertificate(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientCertificate
	 */
	public final java.lang.String getClientCertificate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientCertificate.toString());
	}

	/**
	 * Set value of ClientCertificate
	 * @param clientcertificate
	 */
	public final void setClientCertificate(java.lang.String clientcertificate)
	{
		setClientCertificate(getContext(), clientcertificate);
	}

	/**
	 * Set value of ClientCertificate
	 * @param context
	 * @param clientcertificate
	 */
	public final void setClientCertificate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientcertificate)
	{
		getMendixObject().setValue(context, MemberNames.ClientCertificate.toString(), clientcertificate);
	}

	/**
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey()
	{
		return getClientKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientKey.toString());
	}

	/**
	 * Set value of ClientKey
	 * @param clientkey
	 */
	public final void setClientKey(java.lang.String clientkey)
	{
		setClientKey(getContext(), clientkey);
	}

	/**
	 * Set value of ClientKey
	 * @param context
	 * @param clientkey
	 */
	public final void setClientKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientkey)
	{
		getMendixObject().setValue(context, MemberNames.ClientKey.toString(), clientkey);
	}

	/**
	 * @return value of CertificatePassword
	 */
	public final java.lang.String getCertificatePassword()
	{
		return getCertificatePassword(getContext());
	}

	/**
	 * @param context
	 * @return value of CertificatePassword
	 */
	public final java.lang.String getCertificatePassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CertificatePassword.toString());
	}

	/**
	 * Set value of CertificatePassword
	 * @param certificatepassword
	 */
	public final void setCertificatePassword(java.lang.String certificatepassword)
	{
		setCertificatePassword(getContext(), certificatepassword);
	}

	/**
	 * Set value of CertificatePassword
	 * @param context
	 * @param certificatepassword
	 */
	public final void setCertificatePassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String certificatepassword)
	{
		getMendixObject().setValue(context, MemberNames.CertificatePassword.toString(), certificatepassword);
	}

	/**
	 * Set value of Qos
	 * @param qos
	 */
	public final mqttclient.proxies.qos getQos()
	{
		return getQos(getContext());
	}

	/**
	 * @param context
	 * @return value of Qos
	 */
	public final mqttclient.proxies.qos getQos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Qos.toString());
		if (obj == null)
			return null;

		return mqttclient.proxies.qos.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Qos
	 * @param qos
	 */
	public final void setQos(mqttclient.proxies.qos qos)
	{
		setQos(getContext(), qos);
	}

	/**
	 * Set value of Qos
	 * @param context
	 * @param qos
	 */
	public final void setQos(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.qos qos)
	{
		if (qos != null)
			getMendixObject().setValue(context, MemberNames.Qos.toString(), qos.toString());
		else
			getMendixObject().setValue(context, MemberNames.Qos.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pubSubMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mqttclient.proxies.PubSub that = (mqttclient.proxies.PubSub) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MqttClient.PubSub";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
