// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies;

/**
 * Entity that is responsible to store the onmessage microflow information for the mqtt configuration.
 */
public class Subscription
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MqttClient.Subscription";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OnMessageMicroflow("OnMessageMicroflow"),
		MqttConfig_Subscription("MqttClient.MqttConfig_Subscription");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Subscription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MqttClient.Subscription"));
	}

	protected Subscription(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subscriptionMendixObject)
	{
		if (subscriptionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MqttClient.Subscription", subscriptionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MqttClient.Subscription");

		this.subscriptionMendixObject = subscriptionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Subscription.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mqttclient.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mqttclient.proxies.Subscription.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mqttclient.proxies.Subscription initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mqttclient.proxies.Subscription(context, mendixObject);
	}

	public static mqttclient.proxies.Subscription load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mqttclient.proxies.Subscription.initialize(context, mendixObject);
	}

	public static java.util.List<mqttclient.proxies.Subscription> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mqttclient.proxies.Subscription> result = new java.util.ArrayList<mqttclient.proxies.Subscription>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MqttClient.Subscription" + xpathConstraint))
			result.add(mqttclient.proxies.Subscription.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OnMessageMicroflow
	 */
	public final java.lang.String getOnMessageMicroflow()
	{
		return getOnMessageMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of OnMessageMicroflow
	 */
	public final java.lang.String getOnMessageMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnMessageMicroflow.toString());
	}

	/**
	 * Set value of OnMessageMicroflow
	 * @param onmessagemicroflow
	 */
	public final void setOnMessageMicroflow(java.lang.String onmessagemicroflow)
	{
		setOnMessageMicroflow(getContext(), onmessagemicroflow);
	}

	/**
	 * Set value of OnMessageMicroflow
	 * @param context
	 * @param onmessagemicroflow
	 */
	public final void setOnMessageMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onmessagemicroflow)
	{
		getMendixObject().setValue(context, MemberNames.OnMessageMicroflow.toString(), onmessagemicroflow);
	}

	/**
	 * @return value of MqttConfig_Subscription
	 */
	public final mqttclient.proxies.MqttConfig getMqttConfig_Subscription() throws com.mendix.core.CoreException
	{
		return getMqttConfig_Subscription(getContext());
	}

	/**
	 * @param context
	 * @return value of MqttConfig_Subscription
	 */
	public final mqttclient.proxies.MqttConfig getMqttConfig_Subscription(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mqttclient.proxies.MqttConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MqttConfig_Subscription.toString());
		if (identifier != null)
			result = mqttclient.proxies.MqttConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MqttConfig_Subscription
	 * @param mqttconfig_subscription
	 */
	public final void setMqttConfig_Subscription(mqttclient.proxies.MqttConfig mqttconfig_subscription)
	{
		setMqttConfig_Subscription(getContext(), mqttconfig_subscription);
	}

	/**
	 * Set value of MqttConfig_Subscription
	 * @param context
	 * @param mqttconfig_subscription
	 */
	public final void setMqttConfig_Subscription(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.MqttConfig mqttconfig_subscription)
	{
		if (mqttconfig_subscription == null)
			getMendixObject().setValue(context, MemberNames.MqttConfig_Subscription.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MqttConfig_Subscription.toString(), mqttconfig_subscription.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subscriptionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mqttclient.proxies.Subscription that = (mqttclient.proxies.Subscription) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MqttClient.Subscription";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
