// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies;

/**
 * Entity to hold validation messages.
 */
public class Validation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject validationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MqttClient.Validation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		Message("Message"),
		Validation_MqttConfig("MqttClient.Validation_MqttConfig"),
		Validation_BrokerConfig("MqttClient.Validation_BrokerConfig");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Validation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MqttClient.Validation"));
	}

	protected Validation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject validationMendixObject)
	{
		if (validationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MqttClient.Validation", validationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MqttClient.Validation");

		this.validationMendixObject = validationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Validation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mqttclient.proxies.Validation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mqttclient.proxies.Validation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mqttclient.proxies.Validation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mqttclient.proxies.Validation(context, mendixObject);
	}

	public static mqttclient.proxies.Validation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mqttclient.proxies.Validation.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Status
	 * @param status
	 */
	public final mqttclient.proxies.Enum_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final mqttclient.proxies.Enum_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return mqttclient.proxies.Enum_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(mqttclient.proxies.Enum_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.Enum_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of Validation_MqttConfig
	 */
	public final mqttclient.proxies.MqttConfig getValidation_MqttConfig() throws com.mendix.core.CoreException
	{
		return getValidation_MqttConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of Validation_MqttConfig
	 */
	public final mqttclient.proxies.MqttConfig getValidation_MqttConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mqttclient.proxies.MqttConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Validation_MqttConfig.toString());
		if (identifier != null)
			result = mqttclient.proxies.MqttConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Validation_MqttConfig
	 * @param validation_mqttconfig
	 */
	public final void setValidation_MqttConfig(mqttclient.proxies.MqttConfig validation_mqttconfig)
	{
		setValidation_MqttConfig(getContext(), validation_mqttconfig);
	}

	/**
	 * Set value of Validation_MqttConfig
	 * @param context
	 * @param validation_mqttconfig
	 */
	public final void setValidation_MqttConfig(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.MqttConfig validation_mqttconfig)
	{
		if (validation_mqttconfig == null)
			getMendixObject().setValue(context, MemberNames.Validation_MqttConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Validation_MqttConfig.toString(), validation_mqttconfig.getMendixObject().getId());
	}

	/**
	 * @return value of Validation_BrokerConfig
	 */
	public final mqttclient.proxies.BrokerConfig getValidation_BrokerConfig() throws com.mendix.core.CoreException
	{
		return getValidation_BrokerConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of Validation_BrokerConfig
	 */
	public final mqttclient.proxies.BrokerConfig getValidation_BrokerConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mqttclient.proxies.BrokerConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Validation_BrokerConfig.toString());
		if (identifier != null)
			result = mqttclient.proxies.BrokerConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Validation_BrokerConfig
	 * @param validation_brokerconfig
	 */
	public final void setValidation_BrokerConfig(mqttclient.proxies.BrokerConfig validation_brokerconfig)
	{
		setValidation_BrokerConfig(getContext(), validation_brokerconfig);
	}

	/**
	 * Set value of Validation_BrokerConfig
	 * @param context
	 * @param validation_brokerconfig
	 */
	public final void setValidation_BrokerConfig(com.mendix.systemwideinterfaces.core.IContext context, mqttclient.proxies.BrokerConfig validation_brokerconfig)
	{
		if (validation_brokerconfig == null)
			getMendixObject().setValue(context, MemberNames.Validation_BrokerConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Validation_BrokerConfig.toString(), validation_brokerconfig.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return validationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mqttclient.proxies.Validation that = (mqttclient.proxies.Validation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MqttClient.Validation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
