// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MqttClient module
	public static void iVK_DeletePubSubConfiguration(IContext context, mqttclient.proxies.PubSub _pubSub)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PubSub", _pubSub == null ? null : _pubSub.getMendixObject());
		Core.microflowCall("MqttClient.IVK_DeletePubSubConfiguration").withParams(params).execute(context);
	}
	public static void iVK_SavePubSubConfiguration(IContext context, mqttclient.proxies.PubSub _pubSub)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PubSub", _pubSub == null ? null : _pubSub.getMendixObject());
		Core.microflowCall("MqttClient.IVK_SavePubSubConfiguration").withParams(params).execute(context);
	}
	public static boolean on_Startup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MqttClient.On_Startup").withParams(params).execute(context);
	}
	public static void test_OnMessageMF(IContext context, java.lang.String _payload, java.lang.String _topic, java.lang.String _host, java.lang.Long _port)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payload", _payload);
		params.put("Topic", _topic);
		params.put("Host", _host);
		params.put("Port", _port);
		Core.microflowCall("MqttClient.Test_OnMessageMF").withParams(params).execute(context);
	}
	public static boolean val_PubSubConfiguration(IContext context, mqttclient.proxies.PubSub _pubSub)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PubSub", _pubSub == null ? null : _pubSub.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MqttClient.Val_PubSubConfiguration").withParams(params).execute(context);
	}
}